version: '0.1.{build}'
image: Ubuntu
services:
  - docker
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
branches:
  only:
  - master
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
configuration:
  - Release
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
for:
-
  branches:
    only:
      - master
  build:
    publish_nuget: true
  deploy:
    provider: NuGet
    api_key:
      secure: ajs5P/buZ4+dds+MzCCUEXcy5eHqVID8klG98FZGy/TG3T2hri6FIHw03xwIqD0m
    skip_symbols: true
    artifact: /.*\.nupkg/
